version: '3.8'

services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ny_taxi
    volumes:
      - ./data:/var/lib/postgresql/data:rw

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=arunp77@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - /home
    restart: always
    depends_on:
      - database
    ports:
      - "8080:8080"
